#!/usr/bin/env bash
# http response header
sudo apt-get update
sudo apt-get -y install nginx

# allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# allow us to create files in this directory
sudo chmod -R 755 /var/www

#  create index.html
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# create 404.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# redirect and add header
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# redirect for 404 
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart
sudo service nginx restart
